### ISSUE TITLE
The script excludes the first letter of the folder name.

### ISSUE THREAD

**Issue by DeadlyTitan** [eLTomis/Unity-helper-scripts#1]
Example, if the rootnamespace is MyProject and the folder name is Player the result should be MyProject.Player, but its showing up as MyProject.layer. AM a novice programmer, i tried looking into the issue to try fix it but i couldn't figure out how,

**Comment by Tomeetis** [comment]
Thanks for your insight! 👍🏻

After investigating I've found that there was `projectPath` trimming no matter if it contains 'SCRIPTS' or not. I've fixed it and also added more flexible approach to building a 'trimmed path tree' so that you could have your namespace generation more dynamic.
